# Generated by Django 4.2.1 on 2026-02-09 22:08

from django.db import migrations, models
import django.db.models.deletion
import people.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(blank=True, max_length=200, verbose_name='Street Address')),
                ('postal_code', models.CharField(blank=True, max_length=200, verbose_name='Postal Code')),
                ('city', models.CharField(blank=True, max_length=200, verbose_name='City')),
                ('alternative', models.CharField(blank=True, max_length=1000, verbose_name='Alternative')),
                ('country', models.CharField(blank=True, max_length=200, verbose_name='Country')),
            ],
            options={
                'verbose_name': 'Postal Address',
                'verbose_name_plural': 'Postal Addresses',
                'ordering': ['city', 'street'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('first_name', models.CharField(blank=True, max_length=200, verbose_name='First Name')),
                ('kind', models.CharField(choices=[('oth', 'Other'), ('prs', 'Person'), ('com', 'Company'), ('org', 'Organization')], max_length=3, verbose_name='Kind')),
                ('phone_number', models.CharField(blank=True, max_length=64, verbose_name='Phone')),
                ('cellphone_number', models.CharField(blank=True, max_length=64, verbose_name='Mobile')),
                ('email_address', models.CharField(blank=True, max_length=128, verbose_name='EMail')),
                ('on_address_list', models.BooleanField(default=True, verbose_name='Appears on Adress List')),
                ('is_teammember', models.BooleanField(default=False, verbose_name='Team Member')),
                ('is_societymember', models.BooleanField(default=False, verbose_name='Society Member')),
                ('team_email_address', models.CharField(blank=True, max_length=128, verbose_name='Team-EMail')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='people.address', verbose_name='Postal Address')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ['name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_nr', models.IntegerField(blank=True, default=people.models.Student.get_new_entry_nr, null=True, unique=True, verbose_name='Entry #')),
                ('status', models.CharField(blank=True, choices=[('active', 'Aktiv'), ('in_admission_procedure', 'in admission procedure'), ('waitlisted', 'waitlisted'), ('intent_declared', 'intent declared'), ('cancelled', 'rejected/expired'), ('alumnus', 'alumn'), ('special', 'special')], max_length=32, null=True, verbose_name='Status')),
                ('name', models.CharField(max_length=200, verbose_name='Last Name')),
                ('first_name', models.CharField(max_length=200, verbose_name='First Name')),
                ('short_name', models.CharField(blank=True, max_length=100, verbose_name='Short Name')),
                ('remark', models.CharField(blank=True, max_length=500, null=True, verbose_name='Remark')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('pob', models.CharField(blank=True, max_length=200, null=True, verbose_name='Place of Birth')),
                ('gender', models.CharField(blank=True, choices=[('m', 'male'), ('f', 'female'), ('__', 'other/unspecified')], max_length=2, null=True, verbose_name='Gender')),
                ('denomination', models.CharField(blank=True, max_length=200, null=True, verbose_name='Religious Denomination')),
                ('citizenship', models.CharField(blank=True, max_length=200, null=True, verbose_name='Citizenship')),
                ('language', models.CharField(blank=True, default='Deutsch', max_length=200, verbose_name='Household Language')),
                ('first_day', models.DateField(blank=True, null=True, verbose_name='First day at this School')),
                ('last_day', models.DateField(blank=True, null=True, verbose_name='Last day at this School')),
                ('degree', models.CharField(blank=True, max_length=200, null=True, verbose_name='Degree (when leaving this School)')),
                ('first_enrollment', models.IntegerField(blank=True, null=True, verbose_name='First Enrollment (at any School)')),
                ('level_ofs', models.IntegerField(blank=True, null=True, verbose_name='Class Level (at Reference)')),
                ('level_ref', models.IntegerField(blank=True, null=True, verbose_name='Class Level Reference')),
                ('district_school', models.CharField(blank=True, max_length=200, null=True, verbose_name='District School')),
                ('after_school_care', models.BooleanField(default=False, verbose_name='in After-school Care')),
                ('privacy_policy_agreement', models.BooleanField(null=True, verbose_name='Privacy Policy Agreement')),
                ('vaccination_policy_agreement', models.BooleanField(null=True, verbose_name='Vaccination Policy Agreement')),
                ('vaccination_measles', models.BooleanField(null=True, verbose_name='Measle Vaccination')),
                ('is_sibling', models.BooleanField(null=True, verbose_name='Sibling')),
                ('emergency_notes', models.CharField(blank=True, max_length=400, null=True, verbose_name='Emergency Notes')),
                ('planned_enrollment_year', models.CharField(blank=True, max_length=32, null=True, verbose_name='Enrollment Year')),
                ('planned_enrollment_age', models.CharField(blank=True, max_length=32, null=True, verbose_name='Enrollment Age')),
                ('waitlist_position', models.IntegerField(blank=True, null=True, verbose_name='Waitlist Position')),
                ('application_received', models.BooleanField(null=True, verbose_name='Application received')),
                ('obligatory_conference', models.BooleanField(null=True, verbose_name='was present at obligatory parent conference')),
                ('parent_dialog', models.CharField(blank=True, max_length=32, null=True, verbose_name='Parent Dialog')),
                ('confirmation_status', models.CharField(blank=True, max_length=32, null=True, verbose_name='Confirmation')),
                ('sitting', models.CharField(blank=True, max_length=32, null=True, verbose_name='Sitting In')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='people.address', verbose_name='Postal Address')),
                ('guardians', models.ManyToManyField(blank=True, limit_choices_to={'kind': 'prs'}, related_name='students', to='people.contact', verbose_name='Guardians')),
                ('mentor', models.ForeignKey(blank=True, limit_choices_to={'is_teammember': True, 'kind': 'prs'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentees', to='people.contact', verbose_name='Mentor')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('kind', models.CharField(choices=[('tuition', 'Tuition'), ('materials', 'for Materials'), ('afternoon_care', 'Afternoon Care'), ('other', 'Other')], max_length=20, verbose_name='Kind')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Comment')),
                ('student', models.ForeignKey(limit_choices_to={'status': 'active'}, on_delete=django.db.models.deletion.CASCADE, to='people.student', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Content')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('archived', models.BooleanField(blank=True, default=False, verbose_name='Archived')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.student', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
            },
        ),
    ]
