# Generated by Django 4.2.1 on 2026-02-09 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='kind',
            field=models.CharField(choices=[('oth', 'Other'), ('prs', 'Person'), ('com', 'Company'), ('org', 'Organization'), ('buf', 'Bufdi'), ('int', 'Intern')], max_length=3, verbose_name='Kind'),
        ),
    ]
