# Generated by Django 4.2.1 on 2026-02-21 16:54

from django.db import migrations, models
import django.db.models.deletion
import people.models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_alter_contact_kind'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['city', 'street'], 'verbose_name': 'Postadresse', 'verbose_name_plural': 'Postadressen'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['name', 'first_name'], 'verbose_name': 'Kontakt', 'verbose_name_plural': 'Kontakte'},
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'verbose_name': 'Notiz', 'verbose_name_plural': 'Notizen'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Zahlung', 'verbose_name_plural': 'Zahlungen'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['name', 'first_name'], 'verbose_name': 'Schüler*i', 'verbose_name_plural': 'Schüler*i'},
        ),
        migrations.AddField(
            model_name='contact',
            name='other_kind',
            field=models.CharField(blank=True, max_length=200, verbose_name='Other Kind'),
        ),
        migrations.AlterField(
            model_name='address',
            name='alternative',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Alternativ'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ort'),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(blank=True, max_length=200, verbose_name='Land'),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(blank=True, max_length=200, verbose_name='PLZ'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(blank=True, max_length=200, verbose_name='Straße'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='people.address', verbose_name='Postadresse'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='cellphone_number',
            field=models.CharField(blank=True, max_length=64, verbose_name='Mobil'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Vorname'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='is_societymember',
            field=models.BooleanField(default=False, verbose_name='Trägervereinsmitglied'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='is_teammember',
            field=models.BooleanField(default=False, verbose_name='Teammitglied'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='kind',
            field=models.CharField(choices=[('oth', 'Andere'), ('prs', 'Person'), ('com', 'Firma'), ('org', 'Organisation/Amt/etc'), ('buf', 'Bufdi'), ('int', 'Praktikant*i')], max_length=3, verbose_name='Art'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='note',
            field=models.TextField(blank=True, verbose_name='Notiz'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='on_address_list',
            field=models.BooleanField(default=True, verbose_name='In der Adressliste anzeigen'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(blank=True, max_length=64, verbose_name='Festnetz'),
        ),
        migrations.AlterField(
            model_name='note',
            name='archived',
            field=models.BooleanField(blank=True, default=False, verbose_name='Archiviert'),
        ),
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(verbose_name='Inhalt'),
        ),
        migrations.AlterField(
            model_name='note',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Datum'),
        ),
        migrations.AlterField(
            model_name='note',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.student', verbose_name='Schüler*i'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.FloatField(verbose_name='Betrag'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Anmerkung'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(verbose_name='Datum'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='kind',
            field=models.CharField(choices=[('tuition', 'Schulgeld'), ('materials', 'Materialgeld'), ('afternoon_care', 'Nachmittagsbetreuung'), ('other', 'Andere')], max_length=20, verbose_name='Art'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(limit_choices_to={'status': 'active'}, on_delete=django.db.models.deletion.CASCADE, to='people.student', verbose_name='Schüler*i'),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='people.address', verbose_name='Postadresse'),
        ),
        migrations.AlterField(
            model_name='student',
            name='after_school_care',
            field=models.BooleanField(default=False, verbose_name='in Nachmittagsbetreuung'),
        ),
        migrations.AlterField(
            model_name='student',
            name='application_received',
            field=models.BooleanField(null=True, verbose_name='Bewerbung erhalten'),
        ),
        migrations.AlterField(
            model_name='student',
            name='citizenship',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Staatsbürgerschaft'),
        ),
        migrations.AlterField(
            model_name='student',
            name='confirmation_status',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='(vorl.) Zusage'),
        ),
        migrations.AlterField(
            model_name='student',
            name='degree',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Abschluss (bei Verlassen der Schule)'),
        ),
        migrations.AlterField(
            model_name='student',
            name='denomination',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Religionszugehörigkeit'),
        ),
        migrations.AlterField(
            model_name='student',
            name='district_school',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Einzugsschule'),
        ),
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Geburtsdatum'),
        ),
        migrations.AlterField(
            model_name='student',
            name='emergency_notes',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Notfallhinweise'),
        ),
        migrations.AlterField(
            model_name='student',
            name='entry_nr',
            field=models.IntegerField(blank=True, default=people.models.Student.get_new_entry_nr, null=True, unique=True, verbose_name='Eingangsnummer'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_day',
            field=models.DateField(blank=True, null=True, verbose_name='Erster Tag an dieser Schule'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_enrollment',
            field=models.IntegerField(blank=True, null=True, verbose_name='Erste Einschulung'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=200, verbose_name='Vorname'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'männlich'), ('f', 'weiblich'), ('__', 'anderes/ohne Angabe')], max_length=2, null=True, verbose_name='Geschlecht'),
        ),
        migrations.AlterField(
            model_name='student',
            name='guardians',
            field=models.ManyToManyField(blank=True, limit_choices_to={'kind': 'prs'}, related_name='students', to='people.contact', verbose_name='Erziehungsberechtigte'),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_sibling',
            field=models.BooleanField(null=True, verbose_name='Geschwisterkind'),
        ),
        migrations.AlterField(
            model_name='student',
            name='language',
            field=models.CharField(blank=True, default='Deutsch', max_length=200, verbose_name='Sprache im Elternhaus'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_day',
            field=models.DateField(blank=True, null=True, verbose_name='Letzter Tag an dieser Schule'),
        ),
        migrations.AlterField(
            model_name='student',
            name='level_ofs',
            field=models.IntegerField(blank=True, null=True, verbose_name='Klassenstufe (bei Referenz)'),
        ),
        migrations.AlterField(
            model_name='student',
            name='level_ref',
            field=models.IntegerField(blank=True, null=True, verbose_name='Klassenstufen-Referenz'),
        ),
        migrations.AlterField(
            model_name='student',
            name='mentor',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_teammember': True, 'kind': 'prs'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentees', to='people.contact', verbose_name='Mentor*i'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nachname'),
        ),
        migrations.AlterField(
            model_name='student',
            name='obligatory_conference',
            field=models.BooleanField(null=True, verbose_name='Obl. EA'),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_dialog',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Elterngespräch'),
        ),
        migrations.AlterField(
            model_name='student',
            name='planned_enrollment_age',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Einschulungsalter'),
        ),
        migrations.AlterField(
            model_name='student',
            name='planned_enrollment_year',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Einschulungsjahr'),
        ),
        migrations.AlterField(
            model_name='student',
            name='pob',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Geburtsort'),
        ),
        migrations.AlterField(
            model_name='student',
            name='privacy_policy_agreement',
            field=models.BooleanField(null=True, verbose_name='Datenschutzerklärung'),
        ),
        migrations.AlterField(
            model_name='student',
            name='remark',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Anmerkung'),
        ),
        migrations.AlterField(
            model_name='student',
            name='short_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Rufname'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sitting',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Hospitation'),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Aktiv'), ('in_admission_procedure', 'Bewerbungsverfahren'), ('waitlisted', 'Warteliste'), ('intent_declared', 'Absichtserklärung'), ('cancelled', 'abgesagt/abgelaufen'), ('alumnus', 'Ehemalig'), ('special', 'Ausnahme')], max_length=32, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='student',
            name='vaccination_measles',
            field=models.BooleanField(null=True, verbose_name='Masernschutz besteht'),
        ),
        migrations.AlterField(
            model_name='student',
            name='vaccination_policy_agreement',
            field=models.BooleanField(null=True, verbose_name='Infektionsschutzgesetz'),
        ),
        migrations.AlterField(
            model_name='student',
            name='waitlist_position',
            field=models.IntegerField(blank=True, null=True, verbose_name='Position Warteliste'),
        ),
    ]
